// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHHWnA3wI7cvr820kxgaVw8U5Fs7IOCw',
    appId: '1:1069128128913:web:bfc965937bfd41bdfd2230',
    messagingSenderId: '1069128128913',
    projectId: 'chat-app-3a947',
    authDomain: 'chat-app-3a947.firebaseapp.com',
    storageBucket: 'chat-app-3a947.appspot.com',
    measurementId: 'G-XJZ5JF9NKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkrhfvzxGVDlwWhbCNgPqUI_PQoa35tTY',
    appId: '1:1069128128913:android:d39989ccb0f80e7bfd2230',
    messagingSenderId: '1069128128913',
    projectId: 'chat-app-3a947',
    storageBucket: 'chat-app-3a947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9be54wFuLyTSnWDw71geuyGdPI4Q0RI',
    appId: '1:1069128128913:ios:b7eca478244512f0fd2230',
    messagingSenderId: '1069128128913',
    projectId: 'chat-app-3a947',
    storageBucket: 'chat-app-3a947.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK9be54wFuLyTSnWDw71geuyGdPI4Q0RI',
    appId: '1:1069128128913:ios:b7eca478244512f0fd2230',
    messagingSenderId: '1069128128913',
    projectId: 'chat-app-3a947',
    storageBucket: 'chat-app-3a947.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRHHWnA3wI7cvr820kxgaVw8U5Fs7IOCw',
    appId: '1:1069128128913:web:b8e444a31fd1ad76fd2230',
    messagingSenderId: '1069128128913',
    projectId: 'chat-app-3a947',
    authDomain: 'chat-app-3a947.firebaseapp.com',
    storageBucket: 'chat-app-3a947.appspot.com',
    measurementId: 'G-RQ02BPXW3E',
  );
}
